# import = ["~/.config/alacritty/themes/themes/wombat.toml"]

[shell]
program = "/bin/zsh"

[window]
opacity = 1.0
startup_mode = "Maximized"
padding = { x = 16, y = 4 }
decorations_theme_variant = "Dark"

[scrolling]
multiplier = 5

[colors.primary]
background = "#181818"

[font]
# normal = { family = "HackNerd Font", style = "Regular" }
normal = { family = "JetBrains Mono", style = "Regular" }
#normal = { family = "Iosevka Nerd Font", style = "Regular" }
size = 11.5
offset = { x = 0, y = 0}

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  {key = "PageUp", action = "ScrollLineUp"},
  {key = "PageDown", action = "ScrollLineDown"},
]
